# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiados', '0004_auto_20170825_1150'),
        ('filiados', '0004_auto_20170825_1200'),
    ]

    operations = [
    ]
